fixes column-chart
js-tasks-ru/js-20220209_m-solomahin pull request #8
Opened 2022-02-23 14:40 UTC by MSolomahin

2022-02-23 14:41 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-23 19:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-02-24 20:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-25 18:49 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    const elem = document.querySelectorAll(".notification");
подумайте, можно ли как-то обойтись без обращения к `DOM` для того чтобы понять, присутствует ли в документе нотификейшен.
Подсказка: посмотрите в сторону статического свойства

2022-02-25 18:50 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-02-25 23:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-26 16:38 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (targetTag) {
подумайте, если задать значение по умолчанию для `targetTag` поможет ли это избавиться от конструкции `if...else`?

2022-02-26 16:39 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +      document.getElementById((NotificationMessage.notificationId-1).toString()).remove();
подумайте как избавиться от обращение к `document` в данной проверке

2022-02-26 16:39 UTC, dosandk approved these changes
после разбора домашки на занятии, пожалуйста внесите изменения согласно коментам

2022-02-26 16:39 UTC, merged